import {IPLayerConfig} from "../interf/Player";
import {ICircle, IObstacle} from "../interf/Obstacle";
import {IBoss} from "../interf/Boss";

export const costanti: ICostanti = {
    groundLevel: 320,
    gravity: 0.6,
    jumpForce: -12,
    mainPlayerColor: 'blue',
    obstacleColor: 'red',
    gunColor: 'green',
    bulletColor: 'black',
    isGameOver: false,
    intervalPunteggio: null,
    punteggio: 0,
    obstacleTimer: 0,
    obstacleInterval: 100,
    mainPlayer: null,
    obstacles: [],
    Bullet: null,
    obstacleVelocity: 8,
    canvas: null,
    canvasContext: null,
    upperDiv: null,
    gameFrame: null,
    lowerDiv: null,
    timerShowGun: 0,
    ObstacleShotted: null,
    gameLevel: 1,
    ostacoliAbbattuti: 0,
    lastLevelScore: null,
    enemyBoss: null,
    bossColor: 'green',
    bossHp: 300,
    isBossLifeSpawned: false,
    canvasHeight: 400,
    isShrinking: false,
    bulletDamage: 30
}


interface ICostanti {
    groundLevel: number,
    gravity: number,
    jumpForce: number,
    mainPlayerColor: string,
    obstacleColor: string,
    bulletColor: string,
    gunColor: string,
    isGameOver: boolean,
    intervalPunteggio: null | number,
    punteggio: number,
    obstacleTimer: number,
    obstacleInterval: number,
    mainPlayer: null | IPLayerConfig,
    obstacles: IObstacle[],
    Bullet: ICircle | null,
    obstacleVelocity: number,
    canvas: HTMLCanvasElement | null,
    canvasContext: any | null,
    upperDiv: HTMLElement | null,
    gameFrame: HTMLElement | null,
    lowerDiv: HTMLElement | null,
    timerShowGun: number,
    ObstacleShotted: null | IObstacle,
    gameLevel: number,
    ostacoliAbbattuti: number,
    lastLevelScore: null | number,
    enemyBoss: null | IBoss,
    bossColor: string,
    bossHp: number,
    isBossLifeSpawned: boolean,
    canvasHeight: number,
    isShrinking: boolean,
    bulletDamage: number
}


